apiVersion: v2
name: external-dns-app-bundle
description: Configure external DNS servers for Kubernetes Ingresses and Services with IAM resources
version: ""
appVersion: v0.11.0
home: https://github.com/giantswarm/external-dns-app
icon: https://s.giantswarm.io/app-icons/external-dns/1/dark.png
kubeVersion: ">=1.19.0-0"
sources:
  - https://github.com/kubernetes-sigs/external-dns
  - https://github.com/giantswarm/external-dns-app
annotations:
  application.giantswarm.io/team: team-cabbage
