apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.clusterID }}-external-dns-app-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-dns-app-bundle.labels" $ | nindent 4 }}
data:
  values: |
  {{- (tpl (.Values | toYaml | toString) $) | nindent 4 }}
