apiVersion: v2
appVersion: v0.20.0
description: Configure external DNS servers for Kubernetes Ingresses and Services
home: https://github.com/giantswarm/external-dns-app
icon: https://s.giantswarm.io/app-icons/external-dns/1/dark.png
name: external-dns-app
sources:
  - https://github.com/kubernetes-sigs/external-dns
annotations:
  application.giantswarm.io/team: team-cabbage
version: 3.2.0
kubeVersion: ">=1.19.0-0"
dependencies:
  - name: kubectl-apply-job
    version: "0.11.0"
    repository: oci://giantswarmpublic.azurecr.io/giantswarm-playground-catalog
    condition: crd.install
